### ISSUE TITLE
Doesn't work with cluster

### ISSUE THREAD

**Issue by shumkov** [dscape/lynx#9]
Hello guys,
Very strange situation: I sent timers from [workers](http://nodejs.org/docs/v0.11.11/api/cluster.html) but after few timers (statsd success receive) master is down with error:

```
assert.js:98
  throw new assert.AssertionError({
        ^
AssertionError: false == true
    at SharedHandle.add (cluster.js:77:3)
    at queryServer (cluster.js:402:12)
    at Worker.onmessage (cluster.js:360:7)
    at ChildProcess.<anonymous> (cluster.js:611:8)
    at ChildProcess.EventEmitter.emit (events.js:123:20)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:346:11)
```

**Comment by rmg** [comment]
Upstream: joyent/node#8027
Example workaround: strongloop/strong-agent-statsd#4

**Comment by setthase** [comment]
Also worth of looking at: [sivy/node-statsd#56](https://github.com/sivy/node-statsd/issues/56) and https://github.com/joyent/node/issues/9261

**Comment by setthase** [comment]
Any ETA on this one?
